service: aws-node-simple-http-endpoint

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1024
  timeout: 10
  stage: dev
  region: us-east-1

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: handler.express
    events:
      - http: ANY {proxy+}
      - http: ANY /
